name: WakaTime Readme

on:
  [push,pull_request]:
    branches:
      - main
      - master
      - minzheng
  schedule:
    - cron : '0 21 * * *'

jobs:
  update_readme:
    name: WakaTime Readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        env: 
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY}}
        

